export const LOCAL_MEDIA_START = 'LOCAL_MEDIA_START'
export const LOCAL_MEDIA_STARTED = 'LOCAL_MEDIA_STARTED'
export const LOCAL_MEDIA_STOP = 'LOCAL_MEDIA_STOP'
export const LOCAL_MEDIA_STOPPED = 'LOCAL_MEDIA_STOPPED'

export const OPEN_SFU_UPSTREAM_CONNECTION = 'OPEN_SFU_UPSTREAM_CONNECTION'
export const CLOSE_ALL_CONNECTIONS = 'CLOSE_ALL_CONNECTIONS'

export const ADD_REMOTE_MEDIA = 'ADD_REMOTE_MEDIA'
