export const LOCAL_MEDIA_START = 'LOCAL_MEDIA_START'
export const LOCAL_MEDIA_STARTED = 'LOCAL_MEDIA_STARTED'
export const LOCAL_MEDIA_STOP = 'LOCAL_MEDIA_STOP'
export const LOCAL_MEDIA_STOPPED = 'LOCAL_MEDIA_STOPPED'
