export const OPEN_UPSTREAM_CONNECTION = 'OPEN_UPSTREAM_CONNECTION'
export const CLOSE_ALL_CONNECTIONS = 'CLOSE_ALL_CONNECTIONS'

export const ADD_REMOTE_MEDIA = 'ADD_REMOTE_MEDIA'
export const REMOVE_REMOTE_MEDIA = 'REMOVE_REMOTE_MEDIA'

export const SEND_MESSAGE = 'SEND_MESSAGE'
